### ISSUE TITLE
Clarify collaboration between electron-builder and electron-builder-complete

### ISSUE THREAD

**Issue by stefanjudis** [loopline-systems/electron-builder#138]
> @stefanjudis To be clear — electron-complete-builder is not yet another tool to produce installers, but tool to combine all existing tools to "just publish my electron app".

> As we'll implement the official squirrel thingy
> In this case I will just switch back to use electron-builder again as before.

>Do you want to integrate https://github.com/develar/electron-complete-builder#code-signing, https://github.com/develar/electron-complete-builder#build-version-management and https://github.com/develar/electron-complete-builder/wiki/Publishing-artifacts into electron-builder?

> I ready to create pull requests and do so (e.g. #251, #255). But I think we should follow Unix Philosophy — Do one thing and do it well.

> Do you agree with me or I am wrong? Sorry, but I don't want to have gigantic package.json as you suggest — https://www.npmjs.com/package/electron-builder#how-we-use-it-so-far See my app — https://github.com/develar/onshape-desktop-shell/blob/master/package.json Only one line "release": "npm run compile && build" and app published to GitHub releases.

Taken from here: https://github.com/maxogden/electron-packager/issues/33#issuecomment-182311037

I will have a look later today. :) Thanks. @delevar

**Comment by develar** [comment]
In general, I don't think that end users really need chain `electron-complete-builder` ->  `electron-builder` -> `electron-packager`.

It is not practical. Someone can blame that tool is bloated, but...

Each, each tool currently do to the same thing — read existing `package.json` (and other convenient places) to infer configuration. `electron-complete-builder` does it better than other tools, but it is a temporary situation, I guess (recently, "infer electron version" was implemented in `electron-packager` ). Because it is a vital idea. No one want to maintain gigantic package.json and build scripts. 

Currently, `electron-complete-builder` doesn't reinvent the wheel — only "deb" linux support is a my mistake — definitely, I will use `electron-builder` to build linux installer and get rid of my own prototype implementation (forgot to check it before writing my implementation).

Currently, it is not required to use `electron-builder` to build OS X (`appdmg` used directly, `electron-builder` doesn't add any value) and Windows— [windows-installer](https://github.com/electronjs/windows-installer) used directly to get auto-update ready app.

I cannot say yet how do I see our collaboration — wait your answer to my initial questions.

**Comment by rishson** [comment]
From a user's point of view, both projects are great but I don't think the electron community needs more options.
I agree with @develar that there should just be 1 package that 'just works' :tm: 
`electron-builder` is the better package name and arguable has more traction.
From a personal point of view, could `electron-builder` not become the 1 packager that just works, by adding the extras found in electron-complete-builder, e.g. Squirrel for win32, linux packaging and ci support?
Maybe @develar becoming a committer on `electron-builder` and adding the missing tasks that are in `electron-complete-builder`?
Just think how awesome `electron-builder` would be if you were both contributing to it :smile:

**Comment by stefanjudis** [comment]
> Do you want to integrate https://github.com/develar/electron-complete-builder#code-signing

Code signing makes total sense.

> https://github.com/develar/electron-complete-builder#build-version-management and https://github.com/develar/electron-complete-builder/wiki/Publishing-artifacts

I'm not sure about these but I have to read a bit on these topics. :) When people want to have that's definitely a GO though. :)

> Sorry, but I don't want to have gigantic package.json as you suggest — https://www.npmjs.com/package/electron-builder#how-we-use-it-so-far See my app — https://github.com/develar/onshape-desktop-shell/blob/master/package.json Only one line "release": "npm run compile && build" and app published to GitHub releases.

I totally got that... :) So I see the benefit of `electron-builder-complete`. And I also see that the big config file can be troublesome. Abstracting this aways might be a good idea. :)

**Comment by develar** [comment]
> So I see the benefit of electron-builder-complete

Example: current model (proposed workflow) doesn't allow you to get rid of "OMG, why I should specify it" `executable` parameter in Linux conf. Because `electron-builder` is just a CLI tool and doesn't know anything about `electron-packager`. User must at first execute `pack` and then `build` (I use script task names from https://www.npmjs.com/package/electron-builder#how-we-use-it-so-far)

But `electron-complete-buidler` hides all low-level stuff. Model managed only and only by one tool and all orchestration made only and only by tool. Not by user.

 When I see https://www.npmjs.com/package/electron-builder#build-linux-installer I have only one question — what? why I must specify all of this stuff if tool [can and must infer it](https://github.com/develar/electron-complete-builder/blob/c3d11d61caa531055415b5eb9bc5a754282307ae/src/packager.ts#L390)?

**Comment by stefanjudis** [comment]
@develar 

Yes yes I see. Okay - you're project is in better shape and has more benefit currently.

Honestly I feel like the journey is over here. 

I still would have appreciated discussions and collaboration here in first place, but now it doesn't make much sense to double the work, just because this project was there first.

So what do you think?  We can back link your project here and you can proceed with pushing `electron-builder-complete`.

**Comment by stefanjudis** [comment]
Any opinions from the collaborators? :)

cc. @demetris-manikas @xseignard @mkaz @vQuagliaro @radibit

**Comment by develar** [comment]
> you can proceed with pushing electron-builder-complete

I don't think that it is an option. I am totally agree with your [position](https://github.com/maxogden/electron-packager/issues/33#issuecomment-182324033). 

My proposal: copy `electron-complete-builder` over `electron-builder`.

* `out`: it is a compiler output, not under version control. Maybe renamed (doesn't matter).
* `src`: copy as-is. It is a TS sources. Maybe renamed to reflect content. Code style preserved as-is.
* `test` copy as-is. AVA used, I hope, you don't mind. Maybe `electron-builder` test will be also changed to use AVA, but it should be discussed and addressed in another pull request. Code style is not preserved — reformat to yours.
* `typings`, `tsconfig.json`, `tsd.json` and `tslint.json` copied as is.
* `package.json`: I don't see any conflicts here. Just merge. Current bin scripts copied as is (name).
* `README.md`: I prefer my README — short list of features (links to docs), short info how to configure. `electron-builder` README is a little bit huge. Anyway it should be discussed and addressed in another pull request.

Result:
* Current `electron-builder` behaviour preserved.
* No yet another `builder` tool (even if `electron-complete-builder` currently uses `electron-builder` under the hood). What is more important — for user it will be clear where to file issues like "linux installer doesn't pass Lintian checks".
* `electron--builder` will have all features of `electron-complete-builder`.

**Comment by demetris-manikas** [comment]
Hi to all.
My opinion is that the two projects should somehow merge.
Joined forces will bring better results and will minify confusion to potential users.

**Comment by stefanjudis** [comment]
@develar 

Okay sounds good. So I'd say we open this project by adding collaborators. I'd go by adding @develar and @xseignard as they were the last active contributors. Whoever wants to join - let me know. :)

I haven't had a deep dive into `electron-builder-complete` yet, but I imagine that it's quite a bit of work to merge. But yeah let's do it. :)

I think we can bring further discussions into the issues/prs then and define detailed steps how to proceed.

About `ava` or any testing framework... I don't care at all. ;)

All good with this approach? I'll add collabs then and let's build something great!!! :tada:

**Comment by develar** [comment]
> I'll add collars then

It is not required as far I understand —in any case any my change should be pushed using pull-request. Only if you will be lazy to push and I will do it after your LGTM approval :)

>  I imagine that it's quite a bit of work to merge

Only if you say  — "No, no typescript here — rewrite to ES6". If TS is ok, it will be easy. To be clear — it is much more comfortable to write in TS in the IDE than in ES6 (WebStorm/IntelliJ IDEA).

> I think we can bring further discussions into the issues/prs

I can prepare pull request next week (as stated, only sources&test — README, docs will be addressed in separated pull requests).

**Comment by stefanjudis** [comment]
> It is not required as far I understand —in any case any my change should be pushed using pull-request. 

Jup - I know. But let's open this completely then... Let's create "our" baby here. :) Meaning everyone who wants to can have a voice and proper rights.

> Only if you say — "No, no typescript here — rewrite to ES6". If TS is ok, it will be easy. To be clear — it is much more comfortable to write in TS in the IDE than in ES6 (WebStorm/IntelliJ IDEA).

Haven't used typescript so far.  but yeah why not. ;)

> I can prepare pull request next week (as stated, only sources&test — README, docs will be addressed in separated pull requests).

Sounds great!

**Comment by xseignard** [comment]
IMHO, one tool is a good solution.

I'm not sure `.ts` is a good thing, I may have time to contribute to OSS project, but not to learn yet another language and it is the feeling of many others. `.js` is the lowest common denominator of people who will land here.

This is the only point with I disagree in this thread, but my opinion is not really relevant, since I only did one PR.

Regards!

**Comment by stefanjudis** [comment]
@xseignard But you (!) did the first linux steps. :bowtie: So if you plan to stay on board ( no pressure though ) your opinion is really valuable. :)

**Comment by develar** [comment]
> I'm not sure .ts is a good thing, I may have time to contribute to OSS project, but not to learn yet another language and it is the feeling of many others

TS equals to ES6 + Flow (type syntax). Any JS code is a TS code (except ES7 and other non-standard syntax). And later it can be addressed to just use ES6 (but currently it is much more complex and not easy compare to TS (maintenance cost)).

**Comment by Aluxian** [comment]
@xseignard Sorry, I haven't been following. If you want my opinion about the merge, I think it should be done since it's just a one-time effort. This project is an essential tool for the development of Electron apps, so make it hell awesome!

About the language, I'd say to stick to TS if (and only if) TS supports normal JS, too (and as @develar said, it does). This is so that users who are not familiar with TS can still contribute. If TS is just ES6+Flow then I'm sure anyone can learn it easily, so it shouldn't be a problem.

**Comment by mark-rushakoff** [comment]
I'm new to developing with Electron, and I'm slightly overwhelmed by all the tooling available.

If I followed the discussions correctly, the plan is for electron-builder (this repo) to supersede electron-builder-complete?

If I want to build native executables on a brand new Electron project today, should I use electron-builder?

**Comment by develar** [comment]
@Aluxian Your pack script is a nice example why `electron-complete-builder` was born — you, as an application developer, should be able just run `build` instead of writing own build script to marry various tools. You want to create excellent app, not wasting time to unrelated tasks.

@mark-rushakoff `electron-complete-builder` will be merged and current API will be preserved. I suggest you to use `electron-complete-builder` (because it is much more easy to use and you don't need to write complex configuration) and once it will be merged (next several weeks), you will just change `electron-complete-builder` to `electron-builder` in your `package.json`.

**Comment by develar** [comment]
PR to merge sources: https://github.com/loopline-systems/electron-builder/pull/146

**Comment by havenchyk** [comment]
@stefanjudis @develar guys, do you keep in mind the ability to use `electron-winstaller` as well under the hood of merged `electron-builder`? I'd like to use `electron-winstaller` and do things without the NSIS.

**Comment by develar** [comment]
@havenchyk Answer in code: https://github.com/develar/electron-builder/commit/d977d6ab4cbb696ff43a1f624cc680d2382b94ee (pull request is not yet created, nsis is not yet configured properly on AppVeyor).
 Discussion: https://github.com/loopline-systems/electron-builder/pull/146#issuecomment-184277835
In short: squirrel will be by default, nsis only if `--target=nsis` is specified.
